# Generated by Django 4.2.11 on 2025-06-27 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.maestroitem', verbose_name='Ingrediente')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.medida', verbose_name='Unidad de Medida')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('cantidad_producir', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad a Producir')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('producido', 'Producido')], default='pendiente', max_length=20)),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='orden_produccion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.maestroitem', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCocina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.CharField(max_length=3, unique=True, verbose_name='Código Tipo Documento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('numeracion', models.BooleanField(default=False, verbose_name='Numeración')),
                ('caracteres', models.CharField(max_length=3, verbose_name='Caracteres')),
                ('longitud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('actual', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Actual')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RecetaIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Necesaria')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.ingrediente', verbose_name='Ingrediente')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta', verbose_name='Receta')),
            ],
            options={
                'verbose_name': 'Receta Ingrediente',
                'verbose_name_plural': 'Recetas Ingredientes',
            },
        ),
        migrations.CreateModel(
            name='OrdenProduccionIngrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_necesaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Necesaria')),
                ('cantidad_stock', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad en Stock')),
                ('cantidad_a_comprar', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Cantidad a Comprar')),
                ('precio_compra_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prec.de Comp.Unit')),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.ingrediente', verbose_name='Ingrediente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.ordenproduccion', verbose_name='Orden de Produccion')),
            ],
            options={
                'verbose_name': 'Orden Ingrediente',
                'verbose_name_plural': 'Ordenes Ingredientes',
            },
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocina.receta', verbose_name='Receta'),
        ),
    ]
