# Generated by Django 4.2.11 on 2025-07-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='costo_orden',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo orden'),
        ),
        migrations.AddField(
            model_name='ordenproduccioningrediente',
            name='costo_ingrediente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Ingrediente'),
        ),
    ]
