# Generated by Django 4.2.11 on 2025-07-08 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocina', '0002_ordenproduccion_costo_orden_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccioningrediente',
            name='costo_ingrediente',
        ),
        migrations.AddField(
            model_name='ordenproduccioningrediente',
            name='costo_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Compra'),
        ),
    ]
