# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHabitacion', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Habitación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('valor_noche', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noche')),
                ('ocupada', models.BooleanField(default=False, verbose_name='Ocupada')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoHabitacion', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Habitación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Habitación',
                'verbose_name_plural': 'Tipos Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(default='', max_length=15, unique=True, verbose_name='Consecutivo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('fecha_ingreso', models.DateField(default=None, verbose_name='Fecha Entrada')),
                ('fecha_salida', models.DateField(default=None, verbose_name='Fecha Salida')),
                ('fecha_reserva', models.DateField(default=None, verbose_name='Fecha Reserva')),
                ('valor_reserva', models.FloatField(default=0, verbose_name='Valor Reserva')),
                ('telefono', models.CharField(default='', max_length=50, verbose_name='Teléfono')),
                ('nombre_reserva', models.CharField(default='', max_length=60, verbose_name='Nombre Reserva')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('pin', models.IntegerField(default=0, verbose_name='Pin')),
                ('no_de_dias', models.IntegerField(default=0, verbose_name='Nro. Días')),
                ('no_de_noches', models.IntegerField(default=0, verbose_name='Nro. Noches')),
                ('IdHabitacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion', to='hotel.habitacion', verbose_name='Habitación')),
                ('IdSucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva Habitación',
                'verbose_name_plural': 'Reservas Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consecutivo', models.CharField(default='', max_length=15, unique=True, verbose_name='Consecutivo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('tarifa_habitacion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarifa Habitación')),
                ('check_in', models.DateField(default=None, null=True, verbose_name='Registro Entrada (Check In)')),
                ('hora_check_in', models.TimeField(auto_now=True, null=True, verbose_name='Hora Registro Entrada')),
                ('check_out', models.DateField(default=None, null=True, verbose_name='Registro Salida (check Out)')),
                ('hora_check_out', models.TimeField(default=None, null=True, verbose_name='Hora Registro Salida')),
                ('no_de_dias', models.IntegerField(default=0, verbose_name='Nro. Días')),
                ('no_de_noches', models.IntegerField(default=0, verbose_name='Nro. Noches')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Pago')),
                ('ocupacion', models.CharField(default='', max_length=100, verbose_name='Ocupación')),
                ('empresa', models.CharField(default='', max_length=100, verbose_name='Empresa')),
                ('nacionalidad', models.CharField(default='', max_length=100, verbose_name='Nacionalidad')),
                ('motivo_viaje', models.CharField(choices=[('1', 'Recreación'), ('2', 'Negocios'), ('3', 'Salud'), ('4', 'Otros')], default='1', max_length=1, verbose_name='Motivo Viaje')),
                ('procedencia', models.CharField(default='', max_length=100, verbose_name='Procedencia')),
                ('destino', models.CharField(default='', max_length=100, verbose_name='Destino')),
                ('placa_vehiculo', models.CharField(default='', max_length=10, verbose_name='Placa Vehículo')),
                ('dias_estadia', models.IntegerField(default=0, verbose_name='Días Estadía')),
                ('no_adultos', models.IntegerField(default=0, verbose_name='No. Adultos')),
                ('no_ninos', models.IntegerField(default=0, verbose_name='No. Niños')),
                ('equipaje', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Equipaje')),
                ('consec_reserva', models.CharField(default='', max_length=15, verbose_name='Consec. Reserva')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('no_recibo_caja', models.CharField(default='', max_length=10, verbose_name='Recibo Caja')),
                ('IdHabitacion', models.ForeignKey(max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='registro_habitacion', to='hotel.habitacion', verbose_name='Habitación')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='registro_tercero', to='core.tercero', verbose_name='Cliente:')),
            ],
            options={
                'verbose_name': 'Registro Hotel',
                'verbose_name_plural': 'Registro Hotel',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='IdTipoHabitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_tipo_habitacion', to='hotel.tipohabitacion', verbose_name='Tipo Habitación'),
        ),
        migrations.CreateModel(
            name='AcompañanteHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Nro. Identificación')),
                ('identifica_de', models.CharField(default='', max_length=100, verbose_name='Identificacion de')),
                ('apenom', models.CharField(default='', max_length=80, verbose_name='Nombre')),
                ('lugar_residencia', models.CharField(default='', max_length=80, verbose_name='Lugar Residencia')),
                ('IdRegistro', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acompañante_registro_hotel', to='hotel.registrohotel', verbose_name='RegistroHotel')),
                ('IdTipoIdentificacion', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='acompañante_tipoidentificacion', to='core.tipoidentificacion', verbose_name='Tipo de Indetificación')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
                'ordering': ['identificacion'],
            },
        ),
    ]
