# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('forma_pago', models.CharField(choices=[('CO', 'Contado'), ('CR', 'Crédito')], default='CO', max_length=10, verbose_name='Forma De Pago')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_tercero', to='core.tercero', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Factura Venta',
                'verbose_name_plural': 'Facturas Venta',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFormaPago', models.CharField(max_length=2, unique=True, verbose_name='Código Forma de Pago')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('credito', models.BooleanField(default=False, verbose_name='Crédito')),
            ],
            options={
                'verbose_name': 'Forma de Pago',
                'verbose_name_plural': 'Formas de Pago',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Documento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('numeracion', models.BooleanField(default=False, verbose_name='Numeración')),
                ('caracteres', models.CharField(max_length=3, verbose_name='Caracteres')),
                ('longitud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('actual', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Actual')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdFacturaVenta', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_factura_venta', to='ventas.facturaventa', verbose_name='Recibo Caja')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_tercero', to='core.tercero', verbose_name='Tercero')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_tipodocumento', to='ventas.tipodocumentoventa', verbose_name='Tipo Documento')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Nota Crédito',
                'verbose_name_plural': 'Notas Crédito',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVentaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('por_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Iva')),
                ('val_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Iva')),
                ('por_desc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Descuento')),
                ('val_desc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Descuento')),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Neto')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdFactura', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_detalle_factura', to='ventas.facturaventa', verbose_name='Factura')),
                ('IdItem', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_detalle_item', to='inventarios.maestroitem', verbose_name='Item')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_detalle_tipodocumento', to='ventas.tipodocumentoventa', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Detalle Factura Venta',
                'verbose_name_plural': 'Detalle Facturas Venta',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_tipodocumento', to='ventas.tipodocumentoventa', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='factura_venta_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='CotizacionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_unit', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('por_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Iva')),
                ('val_iva', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Iva')),
                ('por_desc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Descuento')),
                ('val_desc', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Descuento')),
                ('valor_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Neto')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdItem', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_detalle_item', to='inventarios.maestroitem', verbose_name='Item')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_detalle_tipodocumento', to='ventas.tipodocumentoventa', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalle Facturas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('cliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('factura', models.CharField(default='', max_length=10, verbose_name='Factura')),
                ('fecha', models.DateField(blank=True, default=None, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_tipodocumento', to='ventas.tipodocumentoventa', verbose_name='Tipo Documento')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='cotizacion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cotizacion',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['numero'],
            },
        ),
    ]
