# Generated by Django 4.2.11 on 2024-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdReciboCaja',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_recibo_caja', to='caja.recibocaja', verbose_name='Recibo Caja'),
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_tipo_documento', to='caja.tipodocumentocaja', verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_caja', to='caja.caja', verbose_name='Caja No.'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_centro_costo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_caja', to='caja.caja', verbose_name='Caja No.'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdTipoEgreso',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_tipodocumento', to='caja.tipoegresocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
