# Generated by Django 4.2.11 on 2024-04-26 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa'),
        ('caja', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_caja', to='core.tercero', verbose_name='Caja No.'),
        ),
    ]
