# Generated by Django 4.2.11 on 2024-05-02 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_subgrupo_idsubgrupo'),
        ('caja', '0004_alter_recibocaja_idtercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Detalle Pedidos Caja',
                'verbose_name_plural': 'Detalle Pedidos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoIngreso', models.CharField(blank=True, default='', max_length=2, verbose_name='Código Tipo Ingreso')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso Caja',
                'verbose_name_plural': 'Tipos de Ingreso Caja',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='egresocaja',
            options={'ordering': ['numero'], 'verbose_name': 'Egreso Caja', 'verbose_name_plural': 'Egresos Caja'},
        ),
        migrations.CreateModel(
            name='PedidoCajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdItem', models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Detalle Pedidos Caja',
                'verbose_name_plural': 'Detalle Pedidos Caja',
                'ordering': ['numero'],
            },
        ),
    ]
