# Generated by Django 4.2.11 on 2024-05-02 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_ciudad_idciudad_and_more'),
        ('caja', '0005_pedidocaja_tipoingresocaja_alter_egresocaja_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja', to='restaurante.mesa', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdHabitacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipodocumento', to='hotel.habitacion', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_mesa', to='restaurante.mesa', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdReciboCaja',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_recibo_caja', to='caja.recibocaja', verbose_name='Recibo Caja'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdTipoIngreso',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipodocumento', to='caja.tipoingresocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
