# Generated by Django 4.2.11 on 2024-05-03 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_valordefecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurante', '0001_initial'),
        ('caja', '0006_pedidocaja_idcaja_pedidocaja_idhabitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocaja',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición'),
        ),
        migrations.AddField(
            model_name='pedidocajadetalle',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_pedido', to='caja.pedidocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='pedidocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja', to='caja.caja', verbose_name='Tipo Documento'),
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCaja', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja', to='restaurante.mesa', verbose_name='Tipo Documento')),
                ('IdSucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión Caja',
                'verbose_name_plural': 'Sesiones Caja',
                'ordering': ['IdCaja'],
            },
        ),
    ]
