# Generated by Django 4.2.11 on 2024-05-03 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0007_pedidocaja_created_pedidocaja_fecha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['descripcion'], 'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja', to='caja.caja', verbose_name='Caja'),
        ),
    ]
