# Generated by Django 4.2.11 on 2024-05-03 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0008_alter_caja_options_alter_sesioncaja_idcaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesioncaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_caja', to='caja.caja', verbose_name='Caja'),
        ),
    ]
