# Generated by Django 4.2.11 on 2024-05-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0009_alter_sesioncaja_idcaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocaja',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
    ]
