# Generated by Django 4.2.11 on 2024-05-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0010_pedidocaja_cerrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesioncaja',
            name='abierta',
            field=models.BooleanField(default=False, verbose_name='Abierta'),
        ),
    ]
