# Generated by Django 4.2.11 on 2024-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0011_sesioncaja_abierta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocaja',
            name='IdReciboCaja',
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='recibo_caja',
            field=models.CharField(default='', max_length=10, verbose_name='Recibo Caja'),
        ),
    ]
