# Generated by Django 4.2.11 on 2024-05-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
        ('hotel', '0001_initial'),
        ('caja', '0012_remove_pedidocaja_idrecibocaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja', to='caja.caja', verbose_name='Caja'),
        ),
        migrations.AlterField(
            model_name='pedidocaja',
            name='IdHabitacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_habitacion', to='hotel.habitacion', verbose_name='Habitacion'),
        ),
        migrations.AlterField(
            model_name='pedidocaja',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_mesa', to='restaurante.mesa', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='pedidocaja',
            name='IdTipoIngreso',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipoingreso', to='caja.tipoingresocaja', verbose_name='Tipo Ingreso'),
        ),
    ]
