# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0013_alter_pedidocaja_idcaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='idCaja',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código Caja'),
        ),
        migrations.AlterField(
            model_name='egresocaja',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='pedidocaja',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tipodocumentocaja',
            name='idTipo',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código Tipo Documento'),
        ),
        migrations.AlterField(
            model_name='tipoegresocaja',
            name='idTipoEgreso',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código Tipo Egreso'),
        ),
        migrations.AlterField(
            model_name='tipoingresocaja',
            name='idTipoIngreso',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código Tipo Ingreso'),
        ),
    ]
