# Generated by Django 4.2.11 on 2024-05-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0014_alter_caja_idcaja_alter_egresocaja_numero_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidocaja',
            options={'ordering': ['numero'], 'verbose_name': 'Pedidos Caja', 'verbose_name_plural': 'Pedidos Caja'},
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
