# Generated by Django 4.2.11 on 2024-05-31 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_mesa_idmesa'),
        ('core', '0006_alter_pais_idpais_alter_sucursal_idsucursal_and_more'),
        ('hotel', '0002_alter_habitacion_idhabitacion_and_more'),
        ('caja', '0016_pedidocaja_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='IdHabitacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_habitacion', to='hotel.habitacion', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_mesa', to='restaurante.mesa', verbose_name='Mesa'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_tercero', to='core.tercero', verbose_name='Cliente:'),
        ),
    ]
