# Generated by Django 4.2.11 on 2024-06-01 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0017_recibocaja_idhabitacion_recibocaja_idmesa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibocaja',
            old_name='estado',
            new_name='pagado',
        ),
    ]
