# Generated by Django 4.2.11 on 2024-06-04 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_alter_pais_idpais_alter_sucursal_idsucursal_and_more'),
        ('caja', '0018_rename_estado_recibocaja_pagado'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tarjeta Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPagoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Pago',
                'verbose_name_plural': 'Tipos Pago',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='PagoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdReciboCaja', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_recibo_pago', to='caja.recibocaja', verbose_name='Recibo de Caja')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTarjetaCredito', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='Recibo de Caja')),
                ('IdTipoPago', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tipopago', to='caja.tipopagocaja', verbose_name='Tipo Pago')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_centro_costo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago Caja',
                'verbose_name_plural': 'Pagos Caja',
                'ordering': ['numero'],
            },
        ),
    ]
