# Generated by Django 4.2.11 on 2024-06-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0019_tarjetacredito_tipopagocaja_pagocaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocaja',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=2, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_pedido_caja', to='caja.pedidocaja', verbose_name='PedidoCaja:'),
        ),
        migrations.AlterField(
            model_name='pagocaja',
            name='IdTarjetaCredito',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='tarjeta de Crédito'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='pagado',
            field=models.BooleanField(default=False, verbose_name='Pagado'),
        ),
    ]
