# Generated by Django 4.2.11 on 2024-06-11 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('caja', '0020_recibocaja_idpedidocaja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_detalle_tipo_documento', to='caja.tipodocumentocaja', verbose_name='Tipo documento'),
        ),
        migrations.AlterField(
            model_name='pagocaja',
            name='IdTarjetaCredito',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='pago_caja_tarjeta de Crédito'),
        ),
        migrations.AlterField(
            model_name='pagocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_pedido_caja', to='caja.pedidocaja', verbose_name='PedidoCaja:'),
        ),
    ]
