# Generated by Django 4.2.11 on 2024-06-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0021_pagocaja_idtipodocumento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_caja', to='caja.caja', verbose_name='Tipo Pago'),
        ),
    ]
