# Generated by Django 4.2.11 on 2024-06-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0022_pagocaja_idcaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocaja',
            name='IdTarjetaCredito',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='Tarjeta de Crédito'),
        ),
    ]
