# Generated by Django 4.2.11 on 2024-09-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0023_alter_pagocaja_idtarjetacredito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibocaja',
            name='IdPedidoCaja',
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='pedido_caja',
            field=models.CharField(default='', max_length=20, verbose_name='Número'),
        ),
    ]
