# Generated by Django 4.2.11 on 2024-09-05 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0024_remove_recibocaja_idpedidocaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocaja',
            name='IdTercero',
            field=models.CharField(default='', max_length=30, verbose_name='Tercero'),
        ),
    ]
