# Generated by Django 4.2.11 on 2024-09-05 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tercero_options_remove_tercero_idtipotercero_and_more'),
        ('caja', '0025_alter_recibocaja_idtercero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocaja',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_tercero', to='core.tercero', verbose_name='Cliente:'),
        ),
    ]
