# Generated by Django 4.2.11 on 2024-09-10 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0026_alter_recibocaja_idtercero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibocaja',
            name='pedido_caja',
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_pedido_caja', to='caja.pedidocaja', verbose_name='Pedido Caja'),
        ),
    ]
