# Generated by Django 4.2.11 on 2024-09-15 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0027_remove_recibocaja_pedido_caja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_pedido_caja', to='caja.pedidocaja', verbose_name='Pedido Caja'),
        ),
    ]
