# Generated by Django 4.2.11 on 2024-09-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0029_remove_recibocajadetalle_idpedidocaja_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recibocaja',
            name='IdPedidoCaja',
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='pedido_caja',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='padido_caja'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='pedido_caja',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='padido_caja'),
            preserve_default=False,
        ),
    ]
