# Generated by Django 4.2.11 on 2024-09-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0030_remove_recibocaja_idpedidocaja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibocaja',
            name='pedido_caja',
            field=models.CharField(max_length=20, verbose_name='padido_caja'),
        ),
        migrations.AlterField(
            model_name='recibocajadetalle',
            name='pedido_caja',
            field=models.CharField(max_length=20, verbose_name='padido_caja'),
        ),
    ]
