# Generated by Django 4.2.11 on 2024-10-01 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0010_alter_tercero_options_remove_tercero_idtipotercero_and_more'),
        ('caja', '0031_alter_recibocaja_pedido_caja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('recibo_caja', models.CharField(max_length=20, verbose_name='Recibo Caja')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCaja', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_caja', to='caja.caja', verbose_name='Tipo Pago')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTarjetaCredito', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='Tarjeta de Crédito')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tercero', to='core.tercero', verbose_name='Cliente:')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_detalle_tipo_documento', to='caja.tipodocumentocaja', verbose_name='Tipo documento')),
            ],
            options={
                'verbose_name': 'Pago Caja',
                'verbose_name_plural': 'Pagos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterField(
            model_name='recibocaja',
            name='pedido_caja',
            field=models.CharField(max_length=20, verbose_name='Pedido Caja'),
        ),
        migrations.AlterField(
            model_name='recibocajadetalle',
            name='pedido_caja',
            field=models.CharField(max_length=20, verbose_name='Pedido Caja'),
        ),
        migrations.RenameModel(
            old_name='TipoPagoCaja',
            new_name='TipoPagoReciboCaja',
        ),
        migrations.DeleteModel(
            name='PagoCaja',
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdTipoPago',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tipopago', to='caja.tipopagorecibocaja', verbose_name='Tipo Pago'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
