# Generated by Django 4.2.11 on 2024-10-25 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0032_pagorecibocaja_alter_recibocaja_pedido_caja_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagorecibocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_caja', to='caja.caja', verbose_name='Caja Pago'),
        ),
    ]
