# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='idMesa',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Mesa'),
        ),
    ]
