# Generated by Django 4.2.11 on 2024-06-14 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_alter_mesa_idmesa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservamesa',
            name='IdHabitacion',
        ),
        migrations.RemoveField(
            model_name='reservamesa',
            name='idMesa',
        ),
        migrations.AddField(
            model_name='reservamesa',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_mesa', to='restaurante.mesa', verbose_name='Habitación'),
        ),
    ]
