# Generated by Django 4.2.11 on 2024-06-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_remove_reservamesa_idhabitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='en_uso',
            field=models.BooleanField(default=False, verbose_name='En Uso'),
        ),
    ]
