# Generated by Django 4.2.11 on 2024-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_detalle_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_tercero', to='core.tercero', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_tipo_documento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdOrdenCompra',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_tipodocumento', to='compras.ordencompra', verbose_name='Orden Compra'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_cliente', to='core.tercero', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
