# Generated by Django 4.2.11 on 2024-08-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tercero_options_remove_tercero_idtipotercero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0003_alter_despacho_numero_alter_ordencompra_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='IdTercero',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='IdTercero',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdOrden',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_orden_compra', to='compras.ordencompra', verbose_name='Orden Compra'),
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='Nro. Identificación')),
                ('nombre1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Nombre')),
                ('apel1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Apellido')),
                ('apel2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Apellido')),
                ('apenom', models.CharField(default='', max_length=80, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='Razon Social')),
                ('nombre', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('telefono', models.TextField(blank=True, default='', verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, default='', max_length=100, verbose_name='Contacto')),
                ('por_ica', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ica')),
                ('por_ret_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ret Fte')),
                ('valor_debitos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Debitos')),
                ('valor_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Créditos')),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Saldo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCiudad', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_ciudad', to='core.ciudad', verbose_name='Ciudad')),
                ('IdDepartamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento')),
                ('IdPais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_pais', to='core.pais', verbose_name='País')),
                ('IdTipoIdentificacion', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_tipoidentificacion', to='core.tipoidentificacion', verbose_name='Tipo de Indetificación')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['identificacion'],
            },
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_cliente', to='compras.proveedor', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_tercero', to='compras.proveedor', verbose_name='Proveedor'),
        ),
    ]
