# Generated by Django 4.2.11 on 2024-08-08 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0017_entrada_despacho'),
        ('compras', '0004_remove_despacho_idtercero_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalledespacho',
            old_name='cantidad',
            new_name='cantidad_enviada',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='nombre',
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='cantidad_ordenada',
            field=models.IntegerField(default=0, verbose_name='Cantidad'),
        ),
    ]
