# Generated by Django 4.2.11 on 2024-08-08 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_rename_cantidad_detalledespacho_cantidad_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalledespacho',
            name='despacho',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_despacho', to='compras.despacho', verbose_name='Despacho'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_cliente', to='compras.proveedor', verbose_name='Proveedor'),
        ),
    ]
