# Generated by Django 4.2.11 on 2024-08-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_rename_despacho_detalledespacho_iddespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalledespacho',
            name='cantidad_enviada',
            field=models.IntegerField(default=0, verbose_name='Cantidad Enviada'),
        ),
        migrations.AlterField(
            model_name='detalledespacho',
            name='cantidad_ordenada',
            field=models.IntegerField(default=0, verbose_name='Cantidad Ordenada'),
        ),
    ]
