# Generated by Django 4.2.11 on 2024-08-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_detalledespacho_cantidad_enviada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='despacho',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Despacho'),
        ),
    ]
