# Generated by Django 4.2.11 on 2024-08-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0009_ordencompra_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_proveedor', to='compras.proveedor', verbose_name='Proveedor'),
        ),
    ]
