# Generated by Django 4.2.11 on 2024-11-05 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0024_kardex_despacho'),
        ('compras', '0010_alter_ordencompra_idproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdItem', models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario')),
                ('IdProveedor', models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_proveedor', to='compras.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Proveedor Item',
                'verbose_name_plural': 'Proveedores Items',
                'ordering': ['IdItem'],
            },
        ),
    ]
