# Generated by Django 4.2.11 on 2025-02-07 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0039_alter_entrada_anio'),
        ('compras', '0011_proveedoritem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despacho',
            name='IdBodega',
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
    ]
