# Generated by Django 4.2.11 on 2025-02-07 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0012_remove_despacho_idbodega_detalledespacho_idbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalledespacho',
            name='IdBodega',
        ),
    ]
