# Generated by Django 4.2.11 on 2025-02-07 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0013_remove_detalledespacho_idbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='IdBodega',
        ),
    ]
