# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCaja', models.CharField(max_length=2, unique=True, verbose_name='Código Caja')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Base')),
                ('ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingresos')),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egresos')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('consolidada', models.BooleanField(default=False, verbose_name='Consolidada')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='EgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Egreso Caja',
                'verbose_name_plural': 'Egresos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PagoReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('recibo_caja', models.CharField(max_length=20, verbose_name='Recibo Caja')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('estado', models.BooleanField(default=1, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Pago Caja',
                'verbose_name_plural': 'Pagos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('recibo_caja', models.CharField(default='', max_length=10, verbose_name='Recibo Caja')),
                ('total_items', models.IntegerField(default=0, verbose_name='Total Items')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('cerrado', models.BooleanField(default=False, verbose_name='Cerrado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Pedidos Caja',
                'verbose_name_plural': 'Pedidos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='PedidoCajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Detalle Pedidos Caja',
                'verbose_name_plural': 'Detalle Pedidos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('pedido_caja', models.CharField(max_length=20, verbose_name='Pedido Caja')),
                ('registro', models.CharField(max_length=20, verbose_name='No. Registro')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Recibo Caja',
                'verbose_name_plural': 'Recibos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ReciboCajaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('pedido_caja', models.CharField(max_length=20, verbose_name='Pedido Caja')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Detalle Recibo Caja',
                'verbose_name_plural': 'Detalle Recibos Caja',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tarjeta Crédito',
                'verbose_name_plural': 'Tarjetas de Crédito',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.CharField(max_length=3, unique=True, verbose_name='Código Tipo Documento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('numeracion', models.BooleanField(default=False, verbose_name='Numeración')),
                ('caracteres', models.CharField(max_length=3, verbose_name='Caracteres')),
                ('longitud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('actual', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Actual')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoEgresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoEgreso', models.CharField(max_length=2, unique=True, verbose_name='Código Tipo Egreso')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Egreso',
                'verbose_name_plural': 'Tipos de Egreso',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoIngresoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoIngreso', models.CharField(max_length=2, unique=True, verbose_name='Código Tipo Ingreso')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Ingreso Caja',
                'verbose_name_plural': 'Tipos de Ingreso Caja',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoPagoReciboCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Pago',
                'verbose_name_plural': 'Tipos Pago',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abierta', models.BooleanField(default=False, verbose_name='Abierta')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCaja', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_caja', to='caja.caja', verbose_name='Caja')),
                ('IdSucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesion_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Sesión Caja',
                'verbose_name_plural': 'Sesiones Caja',
                'ordering': ['IdCaja'],
            },
        ),
    ]
