# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caja', '0001_initial'),
        ('inventarios', '0001_initial'),
        ('core', '0001_initial'),
        ('hotel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdPedidoCajaDetalle',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_pedido_caja', to='caja.pedidocajadetalle', verbose_name='Pedido Caja'),
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdReciboCaja',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_recibo_caja', to='caja.recibocaja', verbose_name='Recibo Caja'),
        ),
        migrations.AddField(
            model_name='recibocajadetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_detalle_tipo_documento', to='caja.tipodocumentocaja', verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_caja', to='caja.caja', verbose_name='Caja No.'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdHabitacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_habitacion', to='hotel.habitacion', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_mesa', to='restaurante.mesa', verbose_name='Mesa'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_tercero', to='core.tercero', verbose_name='Cliente:'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='recibocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='recibo_caja_centro_costo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pedidocajadetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='pedidocajadetalle',
            name='IdPedidoCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_pedido', to='caja.pedidocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocajadetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_detalle_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja', to='caja.caja', verbose_name='Caja'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdHabitacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_habitacion', to='hotel.habitacion', verbose_name='Habitacion'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdMesa',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_mesa', to='restaurante.mesa', verbose_name='Mesa'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdTipoIngreso',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_tipoingreso', to='caja.tipoingresocaja', verbose_name='Tipo Ingreso'),
        ),
        migrations.AddField(
            model_name='pedidocaja',
            name='IdUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_caja', to='caja.caja', verbose_name='Caja Pago'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdTarjetaCredito',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tarjeta_credito', to='caja.tarjetacredito', verbose_name='Tarjeta de Crédito'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tercero', to='core.tercero', verbose_name='Cliente:'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_detalle_tipo_documento', to='caja.tipodocumentocaja', verbose_name='Tipo documento'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdTipoPago',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_tipopago', to='caja.tipopagorecibocaja', verbose_name='Tipo Pago'),
        ),
        migrations.AddField(
            model_name='pagorecibocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='pago_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdCaja',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_caja', to='caja.caja', verbose_name='Caja No.'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_tipodocumento', to='caja.tipodocumentocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdTipoEgreso',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_tipodocumento', to='caja.tipoegresocaja', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='egresocaja',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='egreso_caja_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
