# Generated by Django 4.2.11 on 2024-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('compras', '0002_initial'),
        ('cxp', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facturacompradetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='facturacompradetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_detalle_tipo_documento', to='cxp.tipodocumentocxp', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdDespacho',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_tipodocumento', to='compras.despacho', verbose_name='Orden Compra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdOrdenCompra',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_tipodocumento', to='compras.ordencompra', verbose_name='Orden Compra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_cliente', to='core.tercero', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_tippodocumento', to='cxp.tipodocumentocxp', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='factura_compra_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
