# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cxp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturacompra',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tipodocumentocxp',
            name='idTipo',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Documento'),
        ),
    ]
