# Generated by Django 4.2.11 on 2024-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cxp', '0002_initial'),
        ('caja', '0002_initial'),
        ('inventarios', '0001_initial'),
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salida',
            name='IdFacturaVenta',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='salida_factura_venta', to='ventas.facturaventa', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='salida',
            name='IdReciboCaja',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='salida_recibo_caja', to='caja.recibocaja', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='salida',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='salida_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='salida',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='salida_tercero', to='core.tercero', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='salida',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='salida_tipodocumento', to='inventarios.tipodocumentoinv', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='salida',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='salida_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='proveedoritem',
            name='IdFacturaCompra',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_factura', to='cxp.facturacompra', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='proveedoritem',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='proveedoritem',
            name='IdOrdenCompra',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_orden_compra', to='compras.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='proveedoritem',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='proveeedor_item_tercero', to='core.tercero', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='maestroitem',
            name='IdGrupo',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='item_grupo', to='inventarios.grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='maestroitem',
            name='IdSubGrupo',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='item_subgrupo', to='inventarios.subgrupo', verbose_name='Subgrupo'),
        ),
        migrations.AddField(
            model_name='maestroitem',
            name='IdUnidadMedida',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='item_unidad_medida', to='inventarios.medida', verbose_name='Unidad de Medida'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='IdEntrada',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_detalle_entrada', to='inventarios.entrada', verbose_name='Entrada Inventario'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_detalle_tipodocumento', to='inventarios.tipodocumentoinv', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdFacturaCompra',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_factura', to='cxp.facturacompra', verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdOrdenCompra',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_orden_compra', to='compras.ordencompra', verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdTercero',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_tercero', to='core.tercero', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_tipodocumento', to='inventarios.tipodocumentoinv', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='bodega_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='acumuladoitem',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='acumulado_Item_bodega', to='inventarios.bodega', verbose_name='Acumulado Bodega'),
        ),
        migrations.AddField(
            model_name='acumuladoitem',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='acumulado_item', to='inventarios.maestroitem', verbose_name='Acumulado Items'),
        ),
        migrations.AddField(
            model_name='acumuladoitem',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='acumulado_item_sucursal', to='core.sucursal', verbose_name='Acumulado Sucursal'),
        ),
    ]
