# Generated by Django 4.2.11 on 2024-04-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgrupo',
            name='idSubGrupo',
            field=models.CharField(blank=True, default='', max_length=3, verbose_name='Código SubGrupo'),
        ),
    ]
