# Generated by Django 4.2.11 on 2024-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_alter_subgrupo_idsubgrupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroitem',
            name='acumula',
            field=models.BooleanField(default='True', verbose_name='Acumula'),
        ),
    ]
