# Generated by Django 4.2.11 on 2024-05-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_maestroitem_acumula'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgrupo',
            name='IdGrupo',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='subgrupo_grupo', to='inventarios.grupo', verbose_name='Grupo'),
        ),
    ]
