# Generated by Django 4.2.11 on 2024-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0005_subgrupo_idgrupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroitem',
            name='imagen',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
