# Generated by Django 4.2.11 on 2024-05-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0006_alter_maestroitem_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroitem',
            name='imagen',
            field=models.ImageField(default='core/static/img/placefolder.png', upload_to='media/'),
        ),
    ]
