# Generated by Django 4.2.11 on 2024-05-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0007_alter_maestroitem_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='idBodega',
            field=models.CharField(blank=True, default='', max_length=3, unique=True, verbose_name='Código Bodega'),
        ),
        migrations.AlterField(
            model_name='entrada',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='idGrupo',
            field=models.CharField(blank=True, default='', max_length=2, unique=True, verbose_name='Código Grupo'),
        ),
        migrations.AlterField(
            model_name='maestroitem',
            name='idItem',
            field=models.CharField(blank=True, default='', max_length=20, unique=True, verbose_name='Código Item'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='idMedida',
            field=models.CharField(blank=True, default='', max_length=2, unique=True, verbose_name='Código Medida'),
        ),
        migrations.AlterField(
            model_name='subgrupo',
            name='idSubGrupo',
            field=models.CharField(blank=True, default='', max_length=3, unique=True, verbose_name='Código SubGrupo'),
        ),
    ]
