# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0008_alter_bodega_idbodega_alter_entrada_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salida',
            name='numero',
            field=models.CharField(max_length=10, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='tipodocumentoinv',
            name='idTipo',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Documento'),
        ),
    ]
