# Generated by Django 4.2.11 on 2024-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0009_alter_salida_numero_alter_tipodocumentoinv_idtipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='responsable',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Responsable'),
        ),
    ]
