# Generated by Django 4.2.11 on 2024-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0010_alter_bodega_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maestroitem',
            name='tipo_producto',
            field=models.CharField(blank=True, choices=[('PT', 'Producto Terminado'), ('MP', 'Materia Prima')], default='PT', max_length=2, verbose_name='Tipo Producto'),
        ),
    ]
