# Generated by Django 4.2.11 on 2024-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0012_acumuladoitem_cant_maxima_acumuladoitem_cant_minima_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='IdFacturaCompra',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='IdOrdenCompra',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='IdFacturaVenta',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='IdReciboCaja',
        ),
        migrations.AddField(
            model_name='entrada',
            name='factura_compra',
            field=models.CharField(default='', max_length=15, verbose_name='Factura'),
        ),
        migrations.AddField(
            model_name='entrada',
            name='orden_compra',
            field=models.CharField(default='', max_length=15, verbose_name='Orden de Compra'),
        ),
        migrations.AddField(
            model_name='salida',
            name='factura_venta',
            field=models.CharField(default='', max_length=15, verbose_name='Factura Venta'),
        ),
        migrations.AddField(
            model_name='salida',
            name='recibo_caja',
            field=models.CharField(default='', max_length=15, verbose_name='Recibo Caja'),
        ),
    ]
