# Generated by Django 4.2.11 on 2024-07-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0013_remove_entrada_idfacturacompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='IdTercero',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='factura_venta',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='recibo_caja',
        ),
        migrations.AddField(
            model_name='salida',
            name='pedido_caja',
            field=models.CharField(default='', max_length=15, verbose_name='Pedido Caja'),
        ),
    ]
