# Generated by Django 4.2.11 on 2024-07-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0014_remove_salida_idtercero_remove_salida_factura_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acumuladoitem',
            name='anio',
            field=models.CharField(default='', max_length=4, verbose_name='Año'),
        ),
    ]
