# Generated by Django 4.2.11 on 2024-08-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0015_acumuladoitem_anio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedoritem',
            name='IdFacturaCompra',
        ),
    ]
