# Generated by Django 4.2.11 on 2024-08-09 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_alter_detalledespacho_cantidad_enviada_and_more'),
        ('inventarios', '0017_entrada_despacho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='IdTercero',
        ),
        migrations.AddField(
            model_name='entrada',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_tercero', to='compras.proveedor', verbose_name='Tercero'),
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='despacho_detalle_id',
            field=models.IntegerField(default=0, verbose_name='Detalle Despacho Id'),
        ),
    ]
