# Generated by Django 4.2.11 on 2024-08-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_alter_ordencompra_idproveedor'),
        ('inventarios', '0018_remove_entrada_idtercero_entrada_idproveedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_proveedor', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.CreateModel(
            name='Kardex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('pedido_caja', models.CharField(default='', max_length=15, verbose_name='Pedido Caja')),
                ('factura_compra', models.CharField(default='', max_length=15, verbose_name='Factura')),
                ('orden_compra', models.CharField(default='', max_length=15, verbose_name='Orden de Compra')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('cantidad', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('saldo', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('tipo_mov', models.CharField(default='', max_length=10, verbose_name='Tipo Movimiento')),
                ('IdItem', models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='kardex_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='kardex_detalle_tipodocumento', to='inventarios.tipodocumentoinv', verbose_name='Tipo Documento')),
            ],
            options={
                'verbose_name': 'Kardex',
                'verbose_name_plural': 'Kardex',
                'ordering': ['numero'],
            },
        ),
    ]
