# Generated by Django 4.2.11 on 2024-08-26 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0020_kardex_idbodega_kardex_idsucursal_alter_kardex_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='maestroitem',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='item_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
    ]
