# Generated by Django 4.2.11 on 2024-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0022_salidadetalle_idpedidodetalle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salidadetalle',
            name='IdPedidoDetalle',
        ),
        migrations.AddField(
            model_name='salidadetalle',
            name='pedido_detalle_id',
            field=models.IntegerField(default=0, verbose_name='Detalle Pedido Id'),
        ),
    ]
