# Generated by Django 4.2.11 on 2024-10-25 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0023_remove_salidadetalle_idpedidodetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardex',
            name='despacho',
            field=models.CharField(default='', max_length=15, verbose_name='Despacho'),
        ),
    ]
