# Generated by Django 4.2.11 on 2024-11-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0025_cierreinventario_inventariofisico'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofisico',
            name='diferencia',
            field=models.IntegerField(default=0, verbose_name='Diferencia'),
        ),
    ]
