# Generated by Django 4.2.11 on 2024-11-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0026_inventariofisico_diferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Ajuste',
                'verbose_name_plural': 'Ajustes',
                'ordering': ['fecha'],
            },
        ),
    ]
