# Generated by Django 4.2.11 on 2024-11-15 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tercero_options_remove_tercero_idtipotercero_and_more'),
        ('inventarios', '0027_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuste',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='ajuste_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='ajuste',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='ajuste_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
    ]
