# Generated by Django 4.2.11 on 2024-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0028_ajuste_idbodega_ajuste_idsucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofisico',
            name='cerrado',
            field=models.BooleanField(default=False, verbose_name='Cerrado'),
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='mes',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default=2024, max_length=12, verbose_name='Mes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventariofisico',
            name='anio',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=4, verbose_name='Año'),
        ),
    ]
