# Generated by Django 4.2.11 on 2024-11-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0029_inventariofisico_cerrado_inventariofisico_mes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventariofisico',
            name='numero_ajuste',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030')], default='', max_length=20, verbose_name='Ajuste'),
            preserve_default=False,
        ),
    ]
