# Generated by Django 4.2.11 on 2024-11-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0030_inventariofisico_numero_ajuste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodega',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Bodega'),
        ),
    ]
