# Generated by Django 4.2.11 on 2024-11-21 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_mes_options_rename_mes_mes_idmes_and_more'),
        ('inventarios', '0031_alter_bodega_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventariofisico',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='inventariofisico',
            name='mes',
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='IdAnio',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_fisico_anio', to='core.anio', verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='IdMes',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='inventario_fisico_mes', to='core.mes', verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='bodega',
            name='descripcion',
            field=models.TextField(blank=True, default='', verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='inventariofisico',
            name='numero_ajuste',
            field=models.CharField(max_length=20, verbose_name='Documento Ajuste'),
        ),
    ]
