# Generated by Django 4.2.11 on 2024-11-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0033_ajusteinventariofisico_delete_ajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajusteinventariofisico',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='ajusteinventariofisico',
            name='numero_ajuste_entrada',
            field=models.CharField(default='', max_length=20, verbose_name='Documento Ajuste Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ajusteinventariofisico',
            name='numero_ajuste_salida',
            field=models.CharField(default='', max_length=20, verbose_name='Documento Ajuste Salida'),
            preserve_default=False,
        ),
    ]
