# Generated by Django 4.2.11 on 2024-11-21 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0034_ajusteinventariofisico_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteinventariofisico',
            name='numero_ajuste_entrada',
            field=models.CharField(default='', max_length=20, verbose_name='Documento Ajuste Entrada'),
        ),
        migrations.AlterField(
            model_name='ajusteinventariofisico',
            name='numero_ajuste_salida',
            field=models.CharField(default='', max_length=20, verbose_name='Documento Ajuste Salida'),
        ),
    ]
