# Generated by Django 4.2.11 on 2025-01-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0035_alter_ajusteinventariofisico_numero_ajuste_entrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='anio',
            field=models.CharField(default='', max_length=4, verbose_name='Anio'),
        ),
        migrations.AddField(
            model_name='salida',
            name='anio',
            field=models.CharField(default='', max_length=4, verbose_name='Anio'),
        ),
    ]
