# Generated by Django 4.2.11 on 2025-01-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0036_entrada_anio_salida_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
    ]
