# Generated by Django 4.2.11 on 2025-01-23 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0037_grupo_idbodega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='IdBodega',
        ),
        migrations.RemoveField(
            model_name='salida',
            name='IdBodega',
        ),
        migrations.AddField(
            model_name='entradadetalle',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_detalle_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
        migrations.AddField(
            model_name='salidadetalle',
            name='IdBodega',
            field=models.ForeignKey(default=1, max_length=3, on_delete=django.db.models.deletion.CASCADE, related_name='salida_detalle_bodega', to='inventarios.bodega', verbose_name='Bodega'),
        ),
    ]
