# Generated by Django 4.2.11 on 2025-02-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0038_remove_entrada_idbodega_remove_salida_idbodega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='anio',
            field=models.CharField(default='', max_length=4, verbose_name='Año'),
        ),
    ]
