# Generated by Django 4.2.11 on 2024-05-02 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_ciudad_idciudad_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHabitacion', models.CharField(blank=True, max_length=3, verbose_name='Código Habitación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('valor_noche', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Noche')),
                ('reserva', models.BooleanField(default=False, verbose_name='Reservada')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoHabitacion', models.CharField(blank=True, max_length=3, verbose_name='Código Tipo Habitación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo Habitación',
                'verbose_name_plural': 'Tipos Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('check_in', models.DateTimeField(default=None)),
                ('check_out', models.DateTimeField(default=None)),
                ('IdHabitacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion', to='hotel.habitacion', verbose_name='Habitación')),
                ('IdSucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva Habitación',
                'verbose_name_plural': 'Reservas Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='IdTipoHabitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='habitacion_tipo_habitacion', to='hotel.tipohabitacion', verbose_name='Tipo Habitación'),
        ),
    ]
