# Generated by Django 4.2.11 on 2025-02-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservaHabitacion',
        ),
    ]
