# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='idHabitacion',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Habitación'),
        ),
        migrations.AlterField(
            model_name='tipohabitacion',
            name='idTipoHabitacion',
            field=models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Habitación'),
        ),
    ]
