# Generated by Django 4.2.11 on 2025-02-20 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('hotel', '0002_delete_reservahabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('check_in', models.DateTimeField(default=None, verbose_name='RegistroHotel Entrada')),
                ('check_out', models.DateTimeField(default=None, verbose_name='RegistroHotel Salida')),
                ('fecha_reserva', models.DateTimeField(default=None, verbose_name='Fecha Reserva')),
                ('valor_reserva', models.FloatField(default=0, verbose_name='Valor Reserva')),
                ('teléfono', models.CharField(default='', max_length=50, verbose_name='Teléfono')),
                ('nombre_reserva', models.CharField(default='', max_length=60, verbose_name='Nombre Reserva')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
                ('pin', models.IntegerField(default=0, verbose_name='Pin')),
                ('no_de_dias', models.IntegerField(default=0, verbose_name='Nro. Días')),
                ('no_de_noches', models.IntegerField(default=0, verbose_name='Nro. Noches')),
                ('IdHabitacion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion', to='hotel.habitacion', verbose_name='Habitación')),
                ('IdSucursal', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_habitacion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reserva Habitación',
                'verbose_name_plural': 'Reservas Habitaciones',
                'ordering': ['descripcion'],
            },
        ),
    ]
