# Generated by Django 4.2.11 on 2025-02-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_habitacion_idhabitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='imagen_habitacion',
            field=models.ImageField(default='0.jpeg', upload_to='media'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='email',
            field=models.CharField(default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='fecha_reserva',
            field=models.DateTimeField(default=None, verbose_name='Fecha Reserva'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='no_de_dias',
            field=models.IntegerField(default=0, verbose_name='Nro. Días'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='no_de_noches',
            field=models.IntegerField(default=0, verbose_name='Nro. Noches'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='nombre_reserva',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre Reserva'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='pin',
            field=models.IntegerField(blank=True, default='', verbose_name='Pin'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='teléfono',
            field=models.CharField(default='', max_length=50, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='reservahabitacion',
            name='valor_reserva',
            field=models.FloatField(default=0, verbose_name='Valor Reserva'),
        ),
        migrations.AlterField(
            model_name='reservahabitacion',
            name='check_in',
            field=models.DateTimeField(default=None, verbose_name='RegistroHotel Entrada'),
        ),
        migrations.AlterField(
            model_name='reservahabitacion',
            name='check_out',
            field=models.DateTimeField(default=None, verbose_name='RegistroHotel Salida'),
        ),
    ]
