# Generated by Django 4.2.11 on 2025-02-20 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_habitacion_imagen_habitacion_reservahabitacion_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='pin',
        ),
    ]
