# Generated by Django 4.2.11 on 2025-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservahabitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen_habitacion',
        ),
        migrations.AddField(
            model_name='tipohabitacion',
            name='imagen_Tipo_habitacion',
            field=models.ImageField(default='0.jpeg', upload_to='media'),
        ),
    ]
