# Generated by Django 4.2.11 on 2025-02-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_reservahabitacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='imagen_habitacion',
        ),
    ]
