# Generated by Django 4.2.11 on 2025-02-20 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_remove_habitacion_imagen_habitacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='imagen_Tipo_habitacion',
        ),
    ]
