# Generated by Django 4.2.11 on 2025-02-20 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_remove_reservahabitacion_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahabitacion',
            name='pin',
            field=models.IntegerField(default=0, verbose_name='Pin'),
        ),
    ]
