# Generated by Django 4.2.11 on 2025-02-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_reservahabitacion_pin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservahabitacion',
            name='pin',
        ),
    ]
