# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Despacho',
                'verbose_name_plural': 'Despacho',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario')),
                ('cantidad_ordenada', models.IntegerField(default=0, verbose_name='Cantidad Ordenada')),
                ('cantidad_enviada', models.IntegerField(default=0, verbose_name='Cantidad Enviada')),
                ('cantidad_unidad_empaque', models.IntegerField(default=0, verbose_name='Cantidad Unidades Empacado')),
                ('cantidad_unidades_enviadas', models.IntegerField(default=0, verbose_name='Cantidad Unidades Enviadas')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Detalle Despacho',
                'verbose_name_plural': 'Detalle Despachos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='EmpaqueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad')),
            ],
            options={
                'verbose_name': 'Empaque',
                'verbose_name_plural': 'Empaques',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('despacho', models.CharField(blank=True, default='', max_length=20, verbose_name='Despacho')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Orden Compra',
                'verbose_name_plural': 'Ordenes Compra',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompraDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor_unidad_empaque', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Cada Empaque')),
                ('valor_compra', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Compra')),
                ('cantidad_unidad_empaque', models.IntegerField(default=0, verbose_name='Cantidad Unidades Empacado')),
                ('cantidad_empaque', models.IntegerField(default=0, verbose_name='Cantidad Empaques Comprados')),
                ('cantidad_unidades_compra', models.IntegerField(default=0, verbose_name='Cantidad Unidades Compradas')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Unitario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Detalle OrdenCompra',
                'verbose_name_plural': 'Detalle OrdenCompra',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='Nro. Identificación')),
                ('nombre1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Nombre')),
                ('apel1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Apellido')),
                ('apel2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Apellido')),
                ('apenom', models.CharField(default='', max_length=80, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='Razon Social')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('telefono', models.TextField(blank=True, default='', verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, default='', max_length=100, verbose_name='Contacto')),
                ('por_ica', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ica')),
                ('por_ret_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ret Fte')),
                ('valor_debitos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Debitos')),
                ('valor_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Créditos')),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Saldo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['identificacion'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Proveedor Item',
                'verbose_name_plural': 'Proveedores Items',
                'ordering': ['IdItem'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.CharField(max_length=3, unique=True, verbose_name='Código Tipo Documento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('numeracion', models.BooleanField(default=False, verbose_name='Numeración')),
                ('caracteres', models.CharField(max_length=3, verbose_name='Caracteres')),
                ('longitud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('actual', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Actual')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
                'ordering': ['descripcion'],
            },
        ),
    ]
