# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedoritem',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='proveedoritem',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_item_proveedor', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IdCiudad',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_ciudad', to='core.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IdDepartamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IdPais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_pais', to='core.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IdTipoIdentificacion',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_tipoidentificacion', to='core.tipoidentificacion', verbose_name='Tipo de Indetificación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdOrden',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_orden_compra', to='compras.ordencompra', verbose_name='Orden Compra'),
        ),
        migrations.AddField(
            model_name='ordencompradetalle',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_detalle_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=15, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_proveedor', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='orden_compra_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='empaqueitem',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='empaque_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdDespacho',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_despacho', to='compras.despacho', verbose_name='Despacho'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdItem',
            field=models.ForeignKey(default=1, max_length=20, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_item', to='inventarios.maestroitem', verbose_name='Item Inventario'),
        ),
        migrations.AddField(
            model_name='detalledespacho',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_detalle_tipo_documento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdOrdenCompra',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_tipodocumento', to='compras.ordencompra', verbose_name='Orden Compra'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdProveedor',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_cliente', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdSucursal',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_sucursal', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdTipoDocumento',
            field=models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_tipodocumento', to='compras.tipodocumentocompra', verbose_name='Tipo Documento'),
        ),
        migrations.AddField(
            model_name='despacho',
            name='IdUsuario',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='despacho_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
