# Generated by Django 4.2.11 on 2025-07-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='IdCiudad',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='IdDepartamento',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Departamento'),
        ),
    ]
