# Generated by Django 4.2.11 on 2025-06-27 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cxc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('cxp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBanco', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Banco')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('sucursal', models.CharField(blank=True, default='', max_length=100, verbose_name='Sucursal')),
                ('cuenta_no', models.CharField(blank=True, default='', max_length=15, verbose_name='Número de Cuenta')),
                ('telefonos', models.CharField(blank=True, default='', max_length=60, verbose_name='Teléfonos')),
                ('responsable', models.CharField(blank=True, default='', max_length=60, verbose_name='Responsable')),
                ('email_respons', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Eesponsable')),
                ('debitos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Débitos')),
                ('creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Créditos')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoTes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipo', models.CharField(blank=True, max_length=3, unique=True, verbose_name='Código Tipo Documento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
                ('numeracion', models.BooleanField(default=False, verbose_name='Numeración')),
                ('caracteres', models.CharField(max_length=3, verbose_name='Caracteres')),
                ('longitud', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Longitud')),
                ('actual', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Actual')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documento',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdFacturaCompra', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_proveedor_factura', to='cxp.facturacompra', verbose_name='Factura')),
                ('IdSucursal', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_proveedor_sucursal', to='core.sucursal', verbose_name='Sucursal')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_proveedor_cliente', to='core.tercero', verbose_name='Cliente')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='pago_proveedor_tipodocumento', to='tesoreria.tipodocumentotes', verbose_name='Tipo Documento')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='pago_proveedor_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pago Proveedor',
                'verbose_name_plural': 'Pago Proveedores',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='IngresoPagoCartera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCartera', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_pago_cartera_actura', to='cxc.cartera', verbose_name='Factura')),
                ('IdTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_pago_cartera_cliente', to='core.tercero', verbose_name='Cliente')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_pago_cartera_tipodocumento', to='tesoreria.tipodocumentotes', verbose_name='Tipo Documento')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='ingreso_pago_cartera_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Ingreso Pago Cartera',
                'verbose_name_plural': 'Ingresos Pago Cartera',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Consignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('detalle', models.TextField(blank=True, default='', verbose_name='Detalle')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdBanco', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='consignacion_banco', to='tesoreria.banco', verbose_name='Banco')),
                ('IdTipoDocumento', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='consignacion_tipodocumento', to='tesoreria.tipodocumentotes', verbose_name='Tipo Documento')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='consignacion_usuario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Consignacion',
                'verbose_name_plural': 'Consignaciones',
                'ordering': ['numero'],
            },
        ),
    ]
