# Generated by Django 4.2.11 on 2024-04-22 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCiudad', models.CharField(max_length=5, verbose_name='Código Ciudad')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudad',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDepartamento', models.CharField(max_length=3, verbose_name='Código Departamento')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPais', models.CharField(max_length=3, verbose_name='Código País')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSucursal', models.CharField(max_length=3, verbose_name='Código Sucursal')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoIdentificacion', models.CharField(max_length=2, verbose_name='Código Identificación')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='TipoTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTipoTercero', models.CharField(max_length=2, verbose_name='Código Tercero')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Tercero',
                'verbose_name_plural': 'Tipos de Terceros',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idTercero', models.CharField(max_length=15, verbose_name='Código Tercero')),
                ('identificacion', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Nro. Identificación')),
                ('nombre1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Nombre')),
                ('nombre2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Nombre')),
                ('apel1', models.CharField(blank=True, default='', max_length=25, verbose_name='Primer Apellido')),
                ('apel2', models.CharField(blank=True, default='', max_length=25, verbose_name='Segundo Apellido')),
                ('apenom', models.CharField(default='', max_length=80, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='Razon Social')),
                ('nombre', models.CharField(blank=True, default='', max_length=70, null=True, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True, default='', verbose_name='Dirección')),
                ('telefono', models.TextField(blank=True, default='', verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True, verbose_name='Email')),
                ('contacto', models.CharField(blank=True, default='', max_length=100, verbose_name='Contacto')),
                ('por_ica', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ica')),
                ('por_ret_fte', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% % Ret Iva')),
                ('valor_debitos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Debitos')),
                ('valor_creditos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Créditos')),
                ('valor_saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Saldo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('IdCiudad', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_ciudad', to='core.ciudad', verbose_name='Ciudad Nacimiento')),
                ('IdDepartamento', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento Nacimiento')),
                ('IdPais', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_pais', to='core.pais', verbose_name='País Nacimiento')),
                ('IdTipoIdentificacion', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_tipoidentificacion', to='core.tipoidentificacion', verbose_name='Tipo de Indetificación')),
                ('IdTipoTercero', models.ForeignKey(default=1, max_length=2, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_tipoidentificacion', to='core.tipotercero', verbose_name='Tipo de Tercero')),
                ('IdUsuario', models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['idTercero'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='IdPais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_pais', to='core.pais', verbose_name='Código País'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='IdDepartamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_departamento', to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='IdPais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad_pais', to='core.pais', verbose_name='País'),
        ),
    ]
