# Generated by Django 4.2.11 on 2024-04-26 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idCiudad',
            field=models.CharField(default=1, max_length=5, verbose_name='Código Ciudad'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='idDepartamento',
            field=models.CharField(default=1, max_length=3, verbose_name='Código Departamento'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='idPais',
            field=models.CharField(default=1, max_length=3, verbose_name='Código País'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='idTercero',
            field=models.CharField(default=1, max_length=15, verbose_name='Código Tercero'),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='idTipoIdentificacion',
            field=models.CharField(default=1, max_length=2, verbose_name='Código Identificación'),
        ),
    ]
