# Generated by Django 4.2.11 on 2024-05-03 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ciudad_idciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorDefecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idValor', models.CharField(default=1, max_length=2, verbose_name='Código Valor')),
                ('Valor', models.CharField(default=1, max_length=10, verbose_name='Valor')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Valor Defecto',
                'verbose_name_plural': 'Valores Defecto',
                'ordering': ['descripcion'],
            },
        ),
    ]
