# Generated by Django 4.2.11 on 2024-05-03 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_valordefecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='valordefecto',
            old_name='Valor',
            new_name='valor',
        ),
    ]
