# Generated by Django 4.2.11 on 2024-05-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_valor_valordefecto_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='idPais',
            field=models.CharField(default=1, max_length=3, unique=True, verbose_name='Código País'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='idSucursal',
            field=models.CharField(max_length=3, unique=True, verbose_name='Código Sucursal'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='idTercero',
            field=models.CharField(default=1, max_length=15, unique=True, verbose_name='Código Tercero'),
        ),
        migrations.AlterField(
            model_name='tipoidentificacion',
            name='idTipoIdentificacion',
            field=models.CharField(default=1, max_length=2, unique=True, verbose_name='Código Identificación'),
        ),
        migrations.AlterField(
            model_name='tipotercero',
            name='idTipoTercero',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código Tercero'),
        ),
        migrations.AlterField(
            model_name='valordefecto',
            name='idValor',
            field=models.CharField(max_length=2, unique=True, verbose_name='Código Valor'),
        ),
    ]
