# Generated by Django 4.2.11 on 2024-06-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_pais_idpais_alter_sucursal_idsucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='IdCiudad',
            field=models.ForeignKey(default=1, max_length=5, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_ciudad', to='core.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='IdDepartamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='IdPais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tercero_pais', to='core.pais', verbose_name='País'),
        ),
    ]
