# Generated by Django 4.2.11 on 2024-07-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_tercero_idciudad_alter_tercero_iddepartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='identificacion',
            field=models.CharField(blank=True, default='', max_length=15, null=True, unique=True, verbose_name='Nro. Identificación'),
        ),
        migrations.AlterField(
            model_name='tercero',
            name='por_ret_fte',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='% Ret Fte'),
        ),
    ]
