# Generated by Django 4.2.11 on 2024-07-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_tercero_identificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tercero',
            name='idTercero',
            field=models.CharField(default=1, max_length=15, verbose_name='Código Tercero'),
        ),
    ]
