# Generated by Django 4.2.11 on 2024-08-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_tercero_idtercero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tercero',
            options={'ordering': ['identificacion'], 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='IdTipoTercero',
        ),
        migrations.RemoveField(
            model_name='tercero',
            name='idTercero',
        ),
        migrations.DeleteModel(
            name='TipoTercero',
        ),
    ]
