# Generated by Django 4.2.11 on 2024-11-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_tercero_options_remove_tercero_idtipotercero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(default='', max_length=4, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Año',
                'verbose_name_plural': 'Años',
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='', max_length=2, verbose_name='Mes')),
                ('descripcion', models.CharField(default='', max_length=15, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Mes',
                'verbose_name_plural': 'Meses',
                'ordering': ['mes'],
            },
        ),
    ]
